################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=HDMI-A-1,2560x1440@144,0x0,1
monitor=eDP-2,2560x1440@165,2560x0,1.25
# unscale XWayland
xwayland {
  force_zero_scaling = true
}

###################
### PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$proxy = clash-verge
$notice = dunst
$bar = waybar
$wallpaper = hyprpaper
$im = fcitx5

# source other config
source = ~/.config/hypr/keybind.hl
source = ~/.config/hypr/ui.hl
source = ~/.config/hypr/input.hl
source = ~/.config/hypr/special.hl

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal & $proxy & $notice
exec-once = $bar & $wallpaper & $im
exec-once = utools

# Load plugins on start up
exec-once = hyprpm reload -n

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/
# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# toolkit-specific scale
env = GDK_SCALE,2

# Multi-GPU
env = WLR_DRM_DEVICES,$HOME/.config/hypr/iGPU:$HOME/.config/hypr/dGPU
