export LC_ALL=en_US.UTF-8
export EDITOR=nvim
export ALIYUNPAN_CONFIG_DIR=/home/w1_liamby/.config/aliyunpan.cfg
export https_proxy=http://127.0.0.1:7899
export http_proxy=http://127.0.0.1:7899
export all_proxy=http://127.0.0.1:7897
export QT_QPA_PLATFORMTHEME=qt5ct
export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json
export XCURSOR_THEME=Bibata-Modern-Classic
export XCURSOR_SIZE=24
export BROWSER=/usr/bin/microsoft-edge-stable
export IMSETTINGS_MODULE=fcitx5
export INPUT_METHOD=fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export GLFW_IM_MODULE=ibus
export XMODIFIERS=@im=fcitx5
export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1
