import = [ "~/.config/alacritty/catppuccin-mocha.toml", ]

[env]
TERM = "xterm-kitty"

[font]
normal = { family = "Maple Mono SC NF", style = "Regular" }
size = 14.0

[window]
padding = { x = 5, y = 5 }
